

# Monitoring and Security Block

- name: Create Glances SYS Monitor container
  docker_container:
    name: "glances-sys-monitor"
    image: "nicolargo/glances"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "8093:61208"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    env: 
        GLANCES_OPT: "-w"


# Proxy App Block
      

- name: NGINX PROXY MANAGER Container
  docker_container:
    name: "NGINX-PROXY-MANAGER"
    image: "jc21/nginx-proxy-manager:latest"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "{{ private_server_ip }}:80:80"
      - "{{ private_server_ip }}:81:81"
      - "{{ private_server_ip }}:443:443"
    volumes:
      - '{{homedir}}/container-program-files/NGINX_PROXY_MANAGER/data:/data'
      - '{{homedir}}/container-program-files/NGINX_PROXY_MANAGER/letsencrypt:/etc/letsencrypt'


# Portainer Block

- name: Create Portainer Agent
  docker_container:
    name: "portainer_agent"
    image: "portainer/agent"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "{{ private_server_ip }}:9091:9001"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'